ALTER SESSION SET CONTAINER = ORCLPDB1;

GRANT CONNECT TO test_user CONTAINER=CURRENT;
GRANT CREATE SESSION TO test_user CONTAINER=CURRENT;
GRANT RESOURCE TO test_user CONTAINER=CURRENT;

ALTER USER test_user QUOTA 100M ON USERS;